### ISSUE TITLE
Kernel crashing issue

### ISSUE THREAD

**Issue by swilliamson7** [EnzymeAD/Enzyme.jl#192] opened 2022-01-28 00:29 UTC
I'm running Julia 1.7.1 in a Jupyter notebook, and my kernel crashes when I try the following:

```julia
f(x) = x'*x
y = [1.0, 2.0]
f_x = zero.(y)

autodiff(f, Duplicated(y, f_x))
```

**Comment by vchuravy** [comment] 2022-01-28 01:11
Fails with:

```
oval=double (i8*, i64, i8*, i64, i8*)* inttoptr (i64 140454831434351 to double (i8*, i64, i8*, i64, i8*)*) icv=0
available inversion for   %29 = load i8*, i8** %28, align 8, !dbg !65, !tbaa !71, !nonnull !4 of   %"'il_phi3" = phi i8* , !dbg !73
available inversion for {} addrspace(10)* %1 of {} addrspace(10)* %"'1"
available inversion for {} addrspace(10)* %0 of {} addrspace(10)* %"'"
available inversion for   %3 = alloca i64, align 16 of   %"'ipa5" = alloca i64, align 16
available inversion for   %30 = ptrtoint i8* %29 to i64, !dbg !73 of   %"'ipc7" = ptrtoint i8* %"'il_phi3" to i64, !dbg !73
available inversion for   %24 = load i8*, i8** %23, align 8, !dbg !65, !tbaa !71, !nonnull !4 of   %"'il_phi" = phi i8* , !dbg !73
available inversion for   %2 = alloca i64, align 16 of   %"'ipa" = alloca i64, align 16
available inversion for   %18 = bitcast i64* %3 to i8* of   %"'ipc6" = bitcast i64* %"'ipa5" to i8*
available inversion for   %17 = bitcast i64* %4 to i8* of   %"'ipc9" = bitcast i64* %"'ipa8" to i8*
available inversion for   %25 = ptrtoint i8* %24 to i64, !dbg !73 of   %"'ipc4" = ptrtoint i8* %"'il_phi" to i64, !dbg !73
available inversion for   %27 = call nonnull {}* @julia.pointer_from_objref({} addrspace(11)* %26) #5, !dbg !65 of   %"'ip_phi2" = phi {}* , !dbg !65
available inversion for   %19 = bitcast i64* %2 to i8* of   %"'ipc" = bitcast i64* %"'ipa" to i8*
available inversion for   %22 = call nonnull {}* @julia.pointer_from_objref({} addrspace(11)* %21) #5, !dbg !65 of   %"'ip_phi" = phi {}* , !dbg !65
available inversion for   %4 = alloca i64, align 16 of   %"'ipa8" = alloca i64, align 16
julia: /workspace/srcdir/Enzyme/enzyme/Enzyme/GradientUtils.cpp:3347: llvm::Value* GradientUtils::invertPointerM(llvm::Value*, llvm::IRBuilder<>&, bool): Assertion `0 && "cannot find deal with ptr that isnt arg"' failed.

```

**Comment by wsmoses** [comment] 2022-01-28 01:14
What OS are you on?

@vchuravy this feels like the lack of function name on Windows.

**Comment by vchuravy** [comment] 2022-01-28 01:16
Nope I reproduced it on Linux (Julia 1.7 & Enzyme 0.8.2)

**Comment by swilliamson7** [comment] 2022-01-28 01:17
I'm on Linux as well!

**Comment by wsmoses** [comment] 2022-01-28 23:31
Hm, in which case the issue is more than just Windows then (this appears to be a ddot call from blas)

**Comment by wsmoses** [comment] 2022-08-06 17:56
With fallback blas support landed, this succeeds now.

**Closed by wsmoses** 2022-08-06 17:56 UTC
