### ISSUE TITLE
Segfault with CUDA kernel that sums two vectors

### ISSUE THREAD

**Issue by luciano-drozda** [EnzymeAD/Enzyme.jl#572] opened 2023-01-04 21:01 UTC
Julia v1.8.2 -- Enzyme v0.10.13 -- Enzyme_jll v0.0.47+0 -- GPUCompiler v0.16.7 -- CUDA v3.12.0

MWE :

```julia

using CUDA
using Enzyme

# CUDA kernel summing two vectors `a` and `b` and storing results in vector `s`
function f!(s, a, b)

  i    = threadIdx().x
  s[i] = a[i] + b[i]
  return nothing

end # f!

# Wrapper for Enzyme call to differentiate `f!` on the GPU
function df!(ds, da, db)

  Enzyme.autodiff_deferred(f!, Const, ds, da, db)
  return nothing

end # df!

# Compute gradients of the operation on the GPU using Enzyme
function diff_add()

  # Instantiate vectors `a` and `b` to be summed
  # and vector `s` where result is stored
  nthread = 4
  a       = rand(nthread) |> cu
  b       = rand(nthread) |> cu
  s       = zero(a)
  
  # Call `df!` to compute gradients on the GPU via Enzyme
  dzds = rand(nthread) |> cu  # some gradient passed to us
  dzda = zero(a)
  dzdb = zero(b)
  ds   = Duplicated(s, dzds)
  da   = Duplicated(a, dzda)
  db   = Duplicated(b, dzdb)
  @cuda threads=nthread df!(ds, da, db)

end # diff_add

diff_add()

```

**Comment by wsmoses** [comment] 2023-01-04 21:16
Can you post the backtrace? and what system (linux, etc) you're on?

**Comment by luciano-drozda** [comment] 2023-01-04 21:25
Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-1160.el7.x86_64
Architecture: x86-64

```
signal (11): Segmentation fault
in expression starting at REPL[6]:1
_ZN4llvm10DwarfDebug23emitInitialLocDirectiveERKNS_15MachineFunctionEj at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZN4llvm10AsmPrinter31emitInitialRawDwarfLocDirectiveERKNS_15MachineFunctionE at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZN4llvm15NVPTXAsmPrinter22emitFunctionEntryLabelEv at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZN4llvm10AsmPrinter18emitFunctionHeaderEv at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZN4llvm10AsmPrinter16emitFunctionBodyEv at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZN4llvm15NVPTXAsmPrinter20runOnMachineFunctionERNS_15MachineFunctionE at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
_ZL21LLVMTargetMachineEmitP23LLVMOpaqueTargetMachineP16LLVMOpaqueModuleRN4llvm17raw_pwrite_streamE19LLVMCodeGenFileTypePPc at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
LLVMTargetMachineEmitToMemoryBuffer at /drozda/julia-1.8.2/bin/../lib/julia/libLLVM-13jl.so (unknown line)
LLVMTargetMachineEmitToMemoryBuffer at /drozda/.julia/packages/LLVM/9gCXO/lib/13/libLLVM_h.jl:947 [inlined]
emit at /drozda/.julia/packages/LLVM/9gCXO/src/targetmachine.jl:45
mcgen at /drozda/.julia/packages/GPUCompiler/hi5Wg/src/mcgen.jl:73
unknown function (ip: 0x2b5b9fe1105f)
_jl_invoke at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2549
macro expansion at /drozda/.julia/packages/TimerOutputs/LHjFw/src/TimerOutput.jl:253 [inlined]
macro expansion at /drozda/.julia/packages/GPUCompiler/hi5Wg/src/driver.jl:430 [inlined]
macro expansion at /drozda/.julia/packages/TimerOutputs/LHjFw/src/TimerOutput.jl:253 [inlined]
macro expansion at /drozda/.julia/packages/GPUCompiler/hi5Wg/src/driver.jl:427 [inlined]
#emit_asm#120 at /drozda/.julia/packages/GPUCompiler/hi5Wg/src/utils.jl:68
emit_asm##kw at /drozda/.julia/packages/GPUCompiler/hi5Wg/src/utils.jl:62 [inlined]
cufunction_compile at /drozda/.julia/packages/CUDA/DfvRa/src/compiler/execution.jl:354
#224 at /drozda/.julia/packages/CUDA/DfvRa/src/compiler/execution.jl:347 [inlined]
JuliaContext at /drozda/.julia/packages/GPUCompiler/hi5Wg/src/driver.jl:76
unknown function (ip: 0x2b5b99e5ce5a)
_jl_invoke at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2549
cufunction_compile at /drozda/.julia/packages/CUDA/DfvRa/src/compiler/execution.jl:346
cached_compilation at /drozda/.julia/packages/GPUCompiler/hi5Wg/src/cache.jl:90
#cufunction#221 at /drozda/.julia/packages/CUDA/DfvRa/src/compiler/execution.jl:299
cufunction at /drozda/.julia/packages/CUDA/DfvRa/src/compiler/execution.jl:292
unknown function (ip: 0x2b5b99e4faff)
_jl_invoke at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2549
macro expansion at /drozda/.julia/packages/CUDA/DfvRa/src/compiler/execution.jl:102 [inlined]
diff_add at ./REPL[5]:18
unknown function (ip: 0x2b5b99e4098f)
_jl_invoke at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2549
jl_apply at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/julia.h:1839 [inlined]
do_call at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/interpreter.c:126
eval_value at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/interpreter.c:215
eval_stmt_value at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/interpreter.c:166 [inlined]
eval_body at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/interpreter.c:612
jl_interpret_toplevel_thunk at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/interpreter.c:750
jl_toplevel_eval_flex at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/toplevel.c:906
jl_toplevel_eval_flex at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/toplevel.c:850
jl_toplevel_eval_flex at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/toplevel.c:850
eval_body at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/interpreter.c:556
eval_body at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/interpreter.c:522
jl_interpret_toplevel_thunk at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/interpreter.c:750
jl_toplevel_eval_flex at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/toplevel.c:906
ijl_toplevel_eval_in at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/toplevel.c:965
eval at ./boot.jl:368 [inlined]
eval_user_input at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:151
repl_backend_loop at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:247
start_repl_backend at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:232
#run_repl#47 at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:369
run_repl at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:355
jfptr_run_repl_64841.clone_1 at /drozda/julia-1.8.2/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2549
#967 at ./client.jl:419
jfptr_YY.967_30403.clone_1 at /drozda/julia-1.8.2/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2549
jl_apply at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/julia.h:1839 [inlined]
jl_f__call_latest at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/builtins.c:774
#invokelatest#2 at ./essentials.jl:729 [inlined]
invokelatest at ./essentials.jl:726 [inlined]
run_main_repl at ./client.jl:404
exec_options at ./client.jl:318
_start at ./client.jl:522
jfptr__start_56736.clone_1 at /drozda/julia-1.8.2/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/gf.c:2549
jl_apply at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/julia.h:1839 [inlined]
true_main at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/jlapi.c:575
jl_repl_entrypoint at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/src/jlapi.c:719
main at julia (unknown line)
__libc_start_main at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x401098)
Allocations: 58177303 (Pool: 58135007; Big: 42296); GC: 47
Segmentation fault
```

**Comment by wsmoses** [comment] 2023-01-10 02:39
I've reproduced this and will look into

**Comment by wsmoses** [comment] 2023-01-29 17:59
@vchuravy this looks to likely require some GPUCompiler/CUDA.jl level investigation?

**Comment by wsmoses** [comment] 2023-01-30 18:02
Duplicate of https://github.com/EnzymeAD/Enzyme.jl/issues/576

**Closed by wsmoses** 2023-01-30 18:02 UTC
