### ISSUE TITLE
getfield calls not supported

### ISSUE THREAD

**Issue by ChrisRackauckas** [EnzymeAD/Enzyme.jl#644] opened 2023-03-03 15:29 UTC
I see https://github.com/EnzymeAD/Enzyme.jl/blob/f3d2868c6f17532cefd015a12020fe082e40e11d/src/compiler.jl#L1788 is caught, but just for reference an MWE:

```julia
using Enzyme
x  = [2.0, 2.0]
tmp = (;A = rand(2,2))
function f(x::Array{Float64}, y::Array{Float64})
    y .= tmp.A * x
    return nothing
end

Enzyme.autodiff(Forward, f, Duplicated(x, bx), Duplicated(y, by)); # Works

Enzyme.autodiff(Reverse, f, Duplicated(x, bx), Duplicated(y, by));
```

```
julia> Enzyme.autodiff(Reverse, f, Duplicated(x, bx), Duplicated(y, by));
ERROR: Enzyme: not yet implemented in reverse mode, jl_getfield
Stacktrace:
 [1] getproperty
   @ ./Base.jl:37
 [2] getproperty
   @ ./Base.jl:0
```

**Comment by wsmoses** [comment] 2023-03-04 03:56
Duplicate of https://github.com/EnzymeAD/Enzyme.jl/issues/176

**Closed by wsmoses** 2023-03-04 03:56 UTC
