### ISSUE TITLE
Incomplete sentence in docstring of `autodiff(::ForwardMode, ...)`

### ISSUE THREAD

**Issue by giordano** [EnzymeAD/Enzyme.jl#752] opened 2023-04-22 01:18 UTC
https://github.com/EnzymeAD/Enzyme.jl/blob/a23e75f6d1cd35f90ec9a534515fde39d20b01c7/src/Enzyme.jl#L239-L241

**Comment by wsmoses** [comment] 2023-04-22 04:02
Duplicate of https://github.com/EnzymeAD/Enzyme.jl/issues/698

**Closed by wsmoses** 2023-04-22 04:02 UTC
