### ISSUE TITLE
Expected not LegalFullUnwrap for potentially last-value phi node

### ISSUE THREAD

**Issue by tpapp** [EnzymeAD/Enzyme.jl#817] opened 2023-05-08 16:38 UTC
I am isolating an MWE from a large function that crashes with Enzyme, for an issue report.

On what combination of Julia (1.8, 1.9.0-rc3) and Enzyme (0.11.1, main) should I do this?

(asking since 1.9 is just around the corner, an [CI tests for it](https://github.com/EnzymeAD/Enzyme.jl/blob/e96c0c5fc41088d611baa65f3ccbd7379552b9d7/.github/workflows/CI.yml#L55))

**Comment by wsmoses** [comment] 2023-05-08 16:42
main and either 1.9 or 1.8.

**Comment by tpapp** [comment] 2023-05-09 09:37
I have been trying to narrow my problem into an MWE but if I remove too much, the problem disappears. It is part of an unpublished research paper so I would prefer to share privately --- I could pack it up into a self-contained repository and share it with you, if you want to look at it.

**Comment by wsmoses** [comment] 2023-05-09 13:42
Yeah that's fine

**Comment by tpapp** [comment] 2023-05-09 14:24
done, you should have received an invite. thanks!

**Comment by vchuravy** [comment] 2023-05-09 16:14
Please update with a valid description of an issue. The issue at hand is not actionable since 1.9 is supported.

Once the specific issue that Tamas is experiencing is reproduced it can have a concrete issue

**Comment by wsmoses** [comment] 2023-05-09 16:16
```llvm

 parent:
L4416:                                            ; preds = %L4416.loopexit, %L3765.L4416_crit_edge
  %1755 = phi double [ %.pre7245, %L3765.L4416_crit_edge ], [ %2119, %L4416.loopexit ], !dbg !2264
  %1756 = phi double [ %.pre7242, %L3765.L4416_crit_edge ], [ %2117, %L4416.loopexit ], !dbg !2264
  %1757 = phi double [ %.pre7239, %L3765.L4416_crit_edge ], [ %2115, %L4416.loopexit ], !dbg !2264
  %1758 = phi double [ %.pre7236, %L3765.L4416_crit_edge ], [ %2113, %L4416.loopexit ], !dbg !2264
  %1759 = phi double [ %.pre7233, %L3765.L4416_crit_edge ], [ %2111, %L4416.loopexit ], !dbg !2264
  %1760 = phi double [ %.pre7230, %L3765.L4416_crit_edge ], [ %2109, %L4416.loopexit ], !dbg !2264
  %1761 = phi double [ %.pre7227, %L3765.L4416_crit_edge ], [ %2107, %L4416.loopexit ], !dbg !2264
  %value_phi439 = phi double [ %value_phi329, %L3765.L4416_crit_edge ], [ %1715, %L4416.loopexit ]
  %1762 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %3) #96, !dbg !2593
  %1763 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1761) #96, !dbg !2264
  %1764 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1760) #96, !dbg !2264
  %1765 = fadd double %1763, %1764, !dbg !2594
  %1766 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1759) #96, !dbg !2264
  %1767 = fadd double %1765, %1766, !dbg !2594
  %1768 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1758) #96, !dbg !2264
  %1769 = fadd double %1767, %1768, !dbg !2594
  %1770 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1757) #96, !dbg !2264
  %1771 = fadd double %1769, %1770, !dbg !2594
  %1772 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1756) #96, !dbg !2264
  %1773 = fadd double %1771, %1772, !dbg !2594
  %1774 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1755) #96, !dbg !2264
  %1775 = fadd double %1773, %1774, !dbg !2594
  %1776 = getelementptr inbounds [1 x [7 x double]], [1 x [7 x double]] addrspace(11)* %1, i64 0, i64 0, i64 0, !dbg !2595
  %1777 = load double, double addrspace(11)* %1776, align 8, !dbg !2264, !tbaa !158, !invariant.load !85, !alias.scope !2601, !noalias !2602
  %1778 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1777) #96, !dbg !2264
  %1779 = getelementptr inbounds [1 x [7 x double]], [1 x [7 x double]] addrspace(11)* %1, i64 0, i64 0, i64 1, !dbg !2595
  %1780 = load double, double addrspace(11)* %1779, align 8, !dbg !2264, !tbaa !158, !invariant.load !85, !alias.scope !2601, !noalias !2602
  %1781 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1780) #96, !dbg !2264
  %1782 = fadd double %1778, %1781, !dbg !2594
  %1783 = getelementptr inbounds [1 x [7 x double]], [1 x [7 x double]] addrspace(11)* %1, i64 0, i64 0, i64 2, !dbg !2595
  %1784 = load double, double addrspace(11)* %1783, align 8, !dbg !2264, !tbaa !158, !invariant.load !85, !alias.scope !2601, !noalias !2602
  %1785 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1784) #96, !dbg !2264
  %1786 = fadd double %1782, %1785, !dbg !2594
  %1787 = getelementptr inbounds [1 x [7 x double]], [1 x [7 x double]] addrspace(11)* %1, i64 0, i64 0, i64 3, !dbg !2595
  %1788 = load double, double addrspace(11)* %1787, align 8, !dbg !2264, !tbaa !158, !invariant.load !85, !alias.scope !2601, !noalias !2602
  %1789 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1788) #96, !dbg !2264
  %1790 = fadd double %1786, %1789, !dbg !2594
  %1791 = getelementptr inbounds [1 x [7 x double]], [1 x [7 x double]] addrspace(11)* %1, i64 0, i64 0, i64 4, !dbg !2595
  %1792 = load double, double addrspace(11)* %1791, align 8, !dbg !2264, !tbaa !158, !invariant.load !85, !alias.scope !2601, !noalias !2602
  %1793 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1792) #96, !dbg !2264
  %1794 = fadd double %1790, %1793, !dbg !2594
  %1795 = getelementptr inbounds [1 x [7 x double]], [1 x [7 x double]] addrspace(11)* %1, i64 0, i64 0, i64 5, !dbg !2595
  %1796 = load double, double addrspace(11)* %1795, align 8, !dbg !2264, !tbaa !158, !invariant.load !85, !alias.scope !2601, !noalias !2602
  %1797 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1796) #96, !dbg !2264
  %1798 = fadd double %1794, %1797, !dbg !2594
  %1799 = getelementptr inbounds [1 x [7 x double]], [1 x [7 x double]] addrspace(11)* %1, i64 0, i64 0, i64 6, !dbg !2595
  %1800 = load double, double addrspace(11)* %1799, align 8, !dbg !2264, !tbaa !158, !invariant.load !85, !alias.scope !2601, !noalias !2602
  %1801 = call fastcc double @julia_normlogpdf_2740(double noundef 0.000000e+00, double noundef 5.000000e+00, double %1800) #96, !dbg !2264
  %1802 = fadd double %1798, %1801, !dbg !2594
  %1803 = bitcast { [1 x [1 x [49 x double]]], double, i64 }* %148 to i8*, !dbg !2603
  call void @llvm.memcpy.p0i8.p11i8.i64(i8* noundef nonnull align 8 dereferenceable(392) %1803, i8 addrspace(11)* nofree noundef nonnull align 8 dereferenceable(392) %238, i64 noundef 392, i1 noundef false) #92, !dbg !2603, !tbaa !188, !alias.scope !189, !noalias !190
  %1804 = getelementptr inbounds { [1 x [1 x [49 x double]]], double, i64 }, { [1 x [1 x [49 x double]]], double, i64 }* %148, i64 0, i32 1, !dbg !2603
  store double 2.000000e+00, double* %1804, align 8, !dbg !2603, !tbaa !239, !alias.scope !241, !noalias !242
  %1805 = getelementptr inbounds { [1 x [1 x [49 x double]]], double, i64 }, { [1 x [1 x [49 x double]]], double, i64 }* %148, i64 0, i32 2, !dbg !2603
  store i64 7, i64* %1805, align 8, !dbg !2603, !tbaa !239, !alias.scope !241, !noalias !242
  %"'ipc1647" = addrspacecast { [1 x [1 x [49 x double]]], double, i64 }* %"'ipa1646" to { [1 x [1 x [49 x double]]], double, i64 } addrspace(11)*, !dbg !2605
  %1806 = addrspacecast { [1 x [1 x [49 x double]]], double, i64 }* %148 to { [1 x [1 x [49 x double]]], double, i64 } addrspace(11)*, !dbg !2605
  %1807 = call fastcc double @julia__mapreduce_2663({ [1 x [1 x [49 x double]]], double, i64 } addrspace(11)* nocapture noundef nonnull readonly align 8 dereferenceable(408) %1806) #98, !dbg !2605
  %1808 = fadd double %1762, %1775, !dbg !2612
  %1809 = fadd double %1808, %1802, !dbg !2612
  %1810 = fadd double %1809, %5938, !dbg !2614
  %1811 = fadd double %value_phi439, %1810, !dbg !2616
  store double %1811, double* %toreturn, align 8, !dbg !2617
  br label %invertL4416, !dbg !2617

 val:   %1715 = fadd double %value_phi393, %1714, !dbg !2373
julia: /home/wmoses/git/Enzyme/enzyme/Enzyme/GradientUtils.cpp:1560: virtual llvm::Value* GradientUtils::unwrapM(llvm::Value*, llvm::IRBuilder<>&, const ValueToValueMapTy&, UnwrapMode, llvm::BasicBlock*, bool): Assertion `unwrapMode != UnwrapMode::LegalFullUnwrap' failed.

[2299873] signal (6.-6): Aborted
in expression starting at /home/wmoses/git/Enzyme.jl/EnzymeBugMWE.jl/replicate_crash.jl:79
pthread_kill at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
raise at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f9c44f9f71a)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unwrapM at /home/wmoses/git/Enzyme/enzyme/Enzyme/GradientUtils.cpp:1560
unwrapM at /home/wmoses/git/Enzyme/enzyme/Enzyme/GradientUtils.cpp:1048
recursivelyHandleSubfunction at /home/wmoses/git/Enzyme/enzyme/Enzyme/AdjointGenerator.h:9502
visitCallInst at /home/wmoses/git/Enzyme/enzyme/Enzyme/AdjointGenerator.h:13241
delegateCallInst at /home/wmoses/.julia/artifacts/661ca8fed2bb0d8cfd97819c42aa9cd8ee260459/include/llvm/IR/InstVisitor.h:302
visitCall at /home/wmoses/.julia/artifacts/661ca8fed2bb0d8cfd97819c42aa9cd8ee260459/include/llvm/IR/Instruction.def:209
visit at /home/wmoses/.julia/artifacts/661ca8fed2bb0d8cfd97819c42aa9cd8ee260459/include/llvm/IR/Instruction.def:209
visit at /home/wmoses/.julia/artifacts/661ca8fed2bb0d8cfd97819c42aa9cd8ee260459/include/llvm/IR/InstVisitor.h:112
CreatePrimalAndGradient at /home/wmoses/git/Enzyme/enzyme/Enzyme/EnzymeLogic.cpp:4119
recursivelyHandleSubfunction at /home/wmoses/git/Enzyme/enzyme/Enzyme/AdjointGenerator.h:9276
visitCallInst at /home/wmoses/git/Enzyme/enzyme/Enzyme/AdjointGenerator.h:13241
delegateCallInst at /home/wmoses/.julia/artifacts/661ca8fed2bb0d8cfd97819c42aa9cd8ee260459/include/llvm/IR/InstVisitor.h:302
visitCall at /home/wmoses/.julia/artifacts/661ca8fed2bb0d8cfd97819c42aa9cd8ee260459/include/llvm/IR/Instruction.def:209
visit at /home/wmoses/.julia/artifacts/661ca8fed2bb0d8cfd97819c42aa9cd8ee260459/include/llvm/IR/Instruction.def:209
visit at /home/wmoses/.julia/artifacts/661ca8fed2bb0d8cfd97819c42aa9cd8ee260459/include/llvm/IR/InstVisitor.h:112
CreatePrimalAndGradient at /home/wmoses/git/Enzyme/enzyme/Enzyme/EnzymeLogic.cpp:4119
EnzymeCreatePrimalAndGradient at /home/wmoses/git/Enzyme/enzyme/Enzyme/CApi.cpp:536
EnzymeCreatePrimalAndGradient at /home/wmoses/git/Enzyme.jl/src/api.jl:128
enzyme! at /home/wmoses/git/Enzyme.jl/src/compiler.jl:7467
unknown function (ip: 0x7f9aff054e5d)
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2758
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
#codegen#197 at /home/wmoses/git/Enzyme.jl/src/compiler.jl:8795
codegen at /home/wmoses/git/Enzyme.jl/src/compiler.jl:8426
unknown function (ip: 0x7f9b0515c791)
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2758
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
_thunk at /home/wmoses/git/Enzyme.jl/src/compiler.jl:9308
_thunk at /home/wmoses/git/Enzyme.jl/src/compiler.jl:9305 [inlined]
cached_compilation at /home/wmoses/git/Enzyme.jl/src/compiler.jl:9343 [inlined]
#s287#226 at /home/wmoses/git/Enzyme.jl/src/compiler.jl:9401 [inlined]
#s287#226 at ./none:0
jl_fptr_args at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2405
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2758
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
GeneratedFunctionStub at ./boot.jl:602
jl_fptr_args at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2405
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2739
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
jl_apply at /home/wmoses/git/Enzyme.jl/julia9/src/julia.h:1879
jl_call_staged at /home/wmoses/git/Enzyme.jl/julia9/src/method.c:530
ijl_code_for_staged at /home/wmoses/git/Enzyme.jl/julia9/src/method.c:581
get_staged at ./compiler/utilities.jl:115
retrieve_code_info at ./compiler/utilities.jl:127 [inlined]
InferenceState at ./compiler/inferencestate.jl:354
typeinf_edge at ./compiler/typeinfer.jl:922
abstract_call_method at ./compiler/abstractinterpretation.jl:611
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:152
abstract_call_known at ./compiler/abstractinterpretation.jl:1949
abstract_call at ./compiler/abstractinterpretation.jl:2020
abstract_call at ./compiler/abstractinterpretation.jl:1999
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2183
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2396
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2684
typeinf_local at ./compiler/abstractinterpretation.jl:2869
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2957
_typeinf at ./compiler/typeinfer.jl:244
typeinf at ./compiler/typeinfer.jl:215
typeinf_ext at ./compiler/typeinfer.jl:1056
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1089
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1085
jfptr_typeinf_ext_toplevel_16504 at /home/wmoses/git/Enzyme.jl/julia9/usr/lib/julia/sys-debug.so (unknown line)
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2739
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
jl_apply at /home/wmoses/git/Enzyme.jl/julia9/src/julia.h:1879
jl_type_infer at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:320
jl_generate_fptr_impl at /home/wmoses/git/Enzyme.jl/julia9/src/jitlayers.cpp:444
jl_compile_method_internal at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2348
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2750
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
autodiff at /home/wmoses/git/Enzyme.jl/src/Enzyme.jl:199
jl_fptr_args at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2405
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2758
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
jl_apply at /home/wmoses/git/Enzyme.jl/julia9/src/julia.h:1879
do_apply at /home/wmoses/git/Enzyme.jl/julia9/src/builtins.c:730
jl_f__apply_iterate at /home/wmoses/git/Enzyme.jl/julia9/src/builtins.c:738
autodiff at /home/wmoses/git/Enzyme.jl/src/Enzyme.jl:214
jl_fptr_args at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2405
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2758
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
jl_apply at /home/wmoses/git/Enzyme.jl/julia9/src/julia.h:1879
do_call at /home/wmoses/git/Enzyme.jl/julia9/src/interpreter.c:126
eval_value at /home/wmoses/git/Enzyme.jl/julia9/src/interpreter.c:226
eval_stmt_value at /home/wmoses/git/Enzyme.jl/julia9/src/interpreter.c:177
eval_body at /home/wmoses/git/Enzyme.jl/julia9/src/interpreter.c:606
jl_interpret_toplevel_thunk at /home/wmoses/git/Enzyme.jl/julia9/src/interpreter.c:762
jl_toplevel_eval_flex at /home/wmoses/git/Enzyme.jl/julia9/src/toplevel.c:912
jl_toplevel_eval_flex at /home/wmoses/git/Enzyme.jl/julia9/src/toplevel.c:856
ijl_toplevel_eval at /home/wmoses/git/Enzyme.jl/julia9/src/toplevel.c:921
ijl_toplevel_eval_in at /home/wmoses/git/Enzyme.jl/julia9/src/toplevel.c:971
eval at ./boot.jl:370 [inlined]
include_string at ./loading.jl:1866
jl_fptr_args at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2405
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2739
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
_include at ./loading.jl:1926
include at ./Base.jl:457
jfptr_include_46840 at /home/wmoses/git/Enzyme.jl/julia9/usr/lib/julia/sys-debug.so (unknown line)
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2739
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
exec_options at ./client.jl:307
_start at ./client.jl:522
jfptr__start_41673 at /home/wmoses/git/Enzyme.jl/julia9/usr/lib/julia/sys-debug.so (unknown line)
_jl_invoke at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2739
ijl_apply_generic at /home/wmoses/git/Enzyme.jl/julia9/src/gf.c:2940
jl_apply at /home/wmoses/git/Enzyme.jl/julia9/src/julia.h:1879
true_main at /home/wmoses/git/Enzyme.jl/julia9/src/jlapi.c:573
jl_repl_entrypoint at /home/wmoses/git/Enzyme.jl/julia9/src/jlapi.c:717
jl_load_repl at /home/wmoses/git/Enzyme.jl/julia9/cli/loader_lib.c:527
main at /home/wmoses/git/Enzyme.jl/julia9/cli/loader_exe.c:59
unknown function (ip: 0x7f9c44fa0d8f)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at ../julia9/julia (unknown line)
Allocations: 87492356 (Pool: 87439913; Big: 52443); GC: 104
Aborted (core dumped)
```

**Comment by wsmoses** [comment] 2023-05-09 16:20
@tpapp I've posted an issue on your private repo with a slight minimization (aka calling now autodiff directly). I need you to remove logdensityproblems and other packages for us to be able to successfully minimize/test/fix this on the LLVM side.

Otherwise this code generates 70k LOC in LLVM and it's a very nontrivial condition that causes this assertion.

**Comment by tpapp** [comment] 2023-05-10 08:23
@vchuravy: apologies, I should have opened another issue, but I was not sure what the problem was. I have added you to the repo, too.

Thanks @wsmoses for filling in the required information.

I have now reduced the dependencies significantly.

**Comment by wsmoses** [comment] 2023-05-14 01:45
This will be fixed by the next jll (which has been tagged on Enzyme proper, and presumably will be in registries for us to merge tomorrow).

**Closed** 2023-05-14 06:25 UTC
