### ISSUE TITLE
constant memory now breaking static arrays

### ISSUE THREAD

**Issue by ExpandingMan** [EnzymeAD/Enzyme.jl#1822] opened 2024-09-13 22:09 UTC
I am reasonably sure this was *NOT* happening before one of the recent patches, and that the previous behavior was correct.

Consider the following
```julia
    f = x -> @SVector([x[1], 0, 0, 0])
    #f = x -> (x[1], 0, 0, 0)

    x = @SVector ones(4)

    Enzyme.autodiff(Enzyme.Forward, f, BatchDuplicatedNoNeed, BatchDuplicated(x, Enzyme.onehot(x)))
```

This fails (on latest tagged 0.12.36) with
```
ERROR: Constant memory is stored (or returned) to a differentiable variable.
As a result, Enzyme cannot provably ensure correctness and throws this error.
This might be due to the use of a constant variable as temporary storage for active memory (https://enzyme.mit.edu/julia/stable/faq/#Activity-of-temporary-storage).
If Enzyme should be able to prove this use non-differentable, open an issue!
To work around this issue, either:
 a) rewrite this variable to not be conditionally active (fastest, but requires a code change), or
 b) set Enzyme.API.runtimeActivity!(true) immediately after loading Enzyme (which maintains correctness, but may slightly reduce performance).
Mismatched activity for:   %.fca.0.1.insert = insertvalue [1 x [4 x double]] %0, double 0.000000e+00, 0, 1, !dbg !19 const val: double 0.000000e+00
Type tree: {[0]:Float@double, [1]:Float@double, [2]:Float@double, [3]:Float@double, [4]:Float@double, [5]:Float@double, [6]:Float@double, [7]:Float@double, [8]:Anything, [9]:Anything, [10]:Anything, [11]:Anything, [12]:Anything, [13]:Anything, [14]:Anything, [15]:Anything, [16]:Float@double, [17]:Float@double, [18]:Float@double, [19]:Float@double, [20]:Float@double, [21]:Float@double, [22]:Float@double, [23]:Float@double, [24]:Float@double, [25]:Float@double, [26]:Float@double, [27]:Float@double, [28]:Float@double, [29]:Float@double, [30]:Float@double, [31]:Float@double}
 llvalue=double 0.000000e+00

Stacktrace:
 [1] #27
   @ ~/.julia/dev/Ricci/test/scrap.jl:0

Stacktrace:
 [1] fwddiffe4julia__27_4955_inner_1wrap
   @ ~/.julia/dev/Ricci/test/scrap.jl:0
 [2] macro expansion
   @ ~/.julia/packages/Enzyme/TiboG/src/compiler.jl:7187 [inlined]
 [3] enzyme_call
   @ ~/.julia/packages/Enzyme/TiboG/src/compiler.jl:6794 [inlined]
 [4] ForwardModeThunk
   @ ~/.julia/packages/Enzyme/TiboG/src/compiler.jl:6674 [inlined]
 [5] autodiff
   @ ~/.julia/packages/Enzyme/TiboG/src/Enzyme.jl:437 [inlined]
 [6] autodiff
   @ ~/.julia/packages/Enzyme/TiboG/src/Enzyme.jl:332 [inlined]
 [7] testdiff1()
   @ Main ~/.julia/dev/Ricci/test/scrap.jl:100
 [8] top-level scope
   @ REPL[10]:1
 [9] top-level scope
   @ none:1
```

However, oddly, it *works* if I replace `f` with the commented line which returns a tuple.  Since `SVector` is just a wrapper of a tuple, I don't think this is correct behavior.  I suspect that something to do with how `@SVector` initializes the array, possibly having to do with `MArray` is causing the problem, though I don't see any evidence for this in the stack trace.

This could probably be worked around in specific cases, but it seems likely that any functions involving `StaticArray` are going to be fragile unless something changes here.

**Comment by wsmoses** [comment] 2024-09-13 22:12
Does this err on main? I think I've fixed the root cause for this a bit earlier?

**Comment by ExpandingMan** [comment] 2024-09-13 22:19
Confirmed works on latest main.  Think some more `StaticArrays` unit tests might be called for, but if you think it's covered now please feel free to close this issue.

**Comment by wsmoses** [comment] 2024-09-13 22:19
Nah, more tests are alway welcome. In any case closing

**Closed by wsmoses** 2024-09-13 22:19 UTC
