### ISSUE TITLE
improve debugging

### ISSUE THREAD

**Issue by tpapp** [EnzymeAD/Enzyme.jl#864] opened 2023-05-23 09:29 UTC
I have been experimenting with this package for my AD needs (for Bayesian inference) for the past few weeks. In the end I concluded that *for the moment*, it is still too buggy for practical use for my purposes (structural economic models), but I would like to keep experimenting with it and help improve it by reporting issues.

I have received amazing help from @wsmoses in #817, #840, #841 and #848, just to mention the last few, and a couple of issues in progress. During various debugging rounds, I found that simply packing up code in a repo with a manifest that replicates the error is not sufficient, the replicating example has to be simple, in the sense of using few external libraries.

I understand that having a simple reproducer for an issue is great. But frequently in the process of I simplify the code the bug just disappears, or turns into *another* bug. So making an MWE of the issue is frequently time-consuming and occasionally frustrating, as it turns into a dead end.

I am wondering if anything could be done to

1. make producing MWEs easier, or alternatively,

2. make larger but self-contained replications of a problem acceptable.

**Comment by wsmoses** [comment] 2023-05-23 18:54
It really depends on the specific issue as to whether a MWE is needed.

E.g. the instruction one was easy and just needed any reproducer. Others may require a lot more specific context.

**Comment by wsmoses** [comment] 2023-06-02 18:40
In the past I know we've tried creduce, @vchuravy may have more suggestions on automatically minimizing an example

**Comment by wsmoses** [comment] 2023-08-09 00:03
since this really doesn't seem actionable as a distinct issue, closing

**Closed by wsmoses** 2023-08-09 00:03 UTC
