### ISSUE TITLE
UndefRefError: access to undefined reference

### ISSUE THREAD

**Issue by wsmoses** [EnzymeAD/Enzyme.jl#293] opened 2022-04-30 23:13 UTC
```
using Enzyme
Enzyme.API.printall!(true)

function bad(@nospecialize(t))
    t = Tuple{t...}
	return Base.unwrap_unionall(t)
end

@show bad((Int64,))
flush(stdout)

@show Enzyme.fwddiff(bad, Duplicated, Duplicated((Int64,), (Int64,))) #,(Int64,)))
```

**Comment by wsmoses** [comment] 2022-08-08 18:32
Now a:
```
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
 [1] unsafe_convert
   @ /mnt/Data/git/Enzyme.jl/src/compiler.jl:4491 [inlined]
 [2] macro expansion
   @ /mnt/Data/git/Enzyme.jl/src/compiler.jl:4734 [inlined]
 [3] enzyme_call
   @ /mnt/Data/git/Enzyme.jl/src/compiler.jl:4530 [inlined]
 [4] ForwardModeThunk
   @ /mnt/Data/git/Enzyme.jl/src/compiler.jl:4515 [inlined]
 [5] autodiff
   @ /mnt/Data/git/Enzyme.jl/src/Enzyme.jl:390 [inlined]
 [6] fwddiff(f::typeof(bad), #unused#::Type{Duplicated}, args::Duplicated{Tuple{DataType}})
   @ Enzyme ./deprecated.jl:72
 [7] top-level scope
   @ show.jl:1047
in expression starting at /mnt/Data/git/Enzyme.jl/appgen.jl:12
```

**Comment by wsmoses** [comment] 2022-08-11 20:03
@vchuravy this variant of the issue is not resolved by your PR.

**Comment by vchuravy** [comment] 2022-08-19 16:59
As far as I can tell duplicate of #347

**Closed** 2022-10-11 01:23 UTC
