### ISSUE TITLE
`empty!` gives error with reverse mode

### ISSUE THREAD

**Issue by jgreener64** [EnzymeAD/Enzyme.jl#882] opened 2023-05-29 22:59 UTC
I am on Julia 1.9.0 and Enzyme 9487eb8349fd7d907403533b53c23822313897bb. This code errors, forward mode works.
```julia
using Enzyme
function f(x)
    y = [1.0, 2.0]
    empty!(y)
    return x
end
autodiff(Reverse, f, Active, Active(1.0))
```
```
ERROR: Enzyme execution failed.
Not applying memset on reverse of jl_array_del_end
Stacktrace:
 [1] _deleteend!
   @ .\array.jl:1023
 [2] empty!
   @ .\array.jl:1773
 [3] f
   @ .\REPL[2]:3
 [4] f
   @ .\REPL[2]:0

Stacktrace:
 [1] throwerr(cstr::Cstring)
   @ Enzyme.Compiler C:\Users\Joe\.julia\dev\Enzyme\src\compiler.jl:2910
```

**Comment by wsmoses** [comment] 2023-06-06 21:15
Duplicate of https://github.com/EnzymeAD/Enzyme.jl/issues/871

**Closed by wsmoses** 2023-06-06 21:15 UTC
