### ISSUE TITLE
sum() sometimes returns incorrect result

### ISSUE THREAD

**Issue by ryanstoner1** [EnzymeAD/Enzyme.jl#397] opened 2022-08-02 13:18 UTC
The gradient of the `sum` function produces varying results for arrays with more than ~1-10 million elements each time it is run. 
```
using Enzyme
n = 1e7
x = ones(convert(Int64,n))
dx = zero(x)
grad = Enzyme.autodiff(sum,Duplicated(x,dx))
print("$(sum(dx))\n")
```
The output should be 1e7 but is often slightly lower because `dx`, which should be populated by 1s has some elements that remain 0s.

**Comment by wsmoses** [comment] 2022-08-02 13:51
There's an index calculation fix in Enzyme proper that hasn't yet been released in a jll for Julia, I'll see if that fixed this and if not investigate.

**Comment by wsmoses** [comment] 2022-08-02 14:19
I'm not able to reproduce this on Enzyme.jl#main with latest Enzyme#main as jll so I'm assuming this is fixed.

When we bump the jll please retry and confirm.

```julia
julia> dx = zero(x);

julia> grad = Enzyme.autodiff(sum,Duplicated(x,dx));

julia> print("$(sum(dx))\n");
1.0e7

julia> dx = zero(x);

julia> grad = Enzyme.autodiff(sum,Duplicated(x,dx));

julia> print("$(sum(dx))\n");
1.0e7
```

**Comment by ryanstoner1** [comment] 2022-08-02 22:19
Ok, running just with the current Enzyme.jl#main still has this issue. @wsmoses

**Comment by wsmoses** [comment] 2022-08-02 22:36
Yeah you don't just need Enzyme.jl$main, you also need Enzyme#main (aka https://github.com/wsmoses/Enzyme which is used by Enzyme.jl as a jll).

**Comment by ryanstoner1** [comment] 2022-08-03 19:57
I see. I'll confirm once you bump the jll.

**Comment by wsmoses** [comment] 2022-08-11 20:23
The jll bump has landed on main. Closing for now, please reopen if you still see this.

**Closed by wsmoses** 2022-08-11 20:23 UTC
Labels: convert to test

**Comment by vchuravy** [comment] 2022-08-11 21:23
Can you add this as a test?
