### ISSUE TITLE
SEGFAULT on Enzyme 0.10.3

### ISSUE THREAD

**Issue by ptiede** [EnzymeAD/Enzyme.jl#573] opened 2023-01-05 23:57 UTC
I am getting a segfault on 0.10.3 that doesn't seem to cause an issue on 0.10.2 (sorry that I wasn't able to simplify the problem more)

```julia
using Enzyme
struct ScaledShiftedLogistic{T}
    scale::T
    shift::T
end

function logistic_logjac(x::Real)
    mx = -abs(x)
    mx - 2*log1p(exp(mx))
end

transform(t::ScaledShiftedLogistic, x::Real) = muladd(inv(exp(-x) + one(x)), t.scale, t.shift)
transform_and_logjac(t::ScaledShiftedLogistic, x::Real) = transform(t, x), log(t.scale) + log1p(exp(-abs(x)))

function enzyme(ss, x)
    res = transform_and_logjac(ss, x)
    return -abs2(first(res)) + last(res)
end

t = ScaledShiftedLogistic(2.0, 0.5)

autodiff(enzyme, Active, Const(t), Active(0.5))
```

I get the following error
```
signal (11): Segmentation fault
in expression starting at /home/ptiede/enzyme_test.jl:25
jl_object_id__cold at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/builtins.c:417
ijl_object_id_ at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/builtins.c:434 [inlined]
ijl_object_id_ at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/builtins.c:422 [inlined]
jl_table_peek_bp at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/iddict.c:119 [inlined]
ijl_eqtable_get at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/iddict.c:158
mtcache_hash_lookup at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/typemap.c:292 [inlined]
mtcache_hash_lookup at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/typemap.c:288 [inlined]
jl_typemap_level_assoc_exact at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/typemap.c:1055
jl_typemap_assoc_exact at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/julia_internal.h:1329 [inlined]
jl_lookup_generic_ at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2499 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2555
enzyme_custom_extract_mi at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/compiler.jl:4729
unknown function (ip: 0x7fa3cdd35b3d)
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
julia_type_rule at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/compiler.jl:4743
unknown function (ip: 0x7fa3cdd33a3c)
operator() at /workspace/srcdir/Enzyme/enzyme/Enzyme/CApi.cpp:209 [inlined]
_M_invoke at /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/8.1.0/bits/std_function.h:282
operator() at /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/8.1.0/bits/std_function.h:687 [inlined]
visitCallInst at /workspace/srcdir/Enzyme/enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp:3608
visitValue at /workspace/srcdir/Enzyme/enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp:1171
run at /workspace/srcdir/Enzyme/enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp:1100
analyzeFunction at /workspace/srcdir/Enzyme/enzyme/Enzyme/TypeAnalysis/TypeAnalysis.cpp:5046
CreateFromClone at /workspace/srcdir/Enzyme/enzyme/Enzyme/GradientUtils.cpp:3754
CreatePrimalAndGradient at /workspace/srcdir/Enzyme/enzyme/Enzyme/EnzymeLogic.cpp:3704
EnzymeCreatePrimalAndGradient at /workspace/srcdir/Enzyme/enzyme/Enzyme/CApi.cpp:474
EnzymeCreatePrimalAndGradient at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/api.jl:123
enzyme! at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/compiler.jl:5049
unknown function (ip: 0x7fa3cdd2fee2)
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
#codegen#142 at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/compiler.jl:6242
codegen##kw at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/compiler.jl:5911 [inlined]
_thunk at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/compiler.jl:6729 [inlined]
_thunk at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/compiler.jl:6723
unknown function (ip: 0x7fa41cf999ad)
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
cached_compilation at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/compiler.jl:6767
unknown function (ip: 0x7fa41cf745a3)
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
#s879#169 at /home/ptiede/.julia/packages/Enzyme/I25Pv/src/compiler.jl:6827 [inlined]
#s879#169 at ./none:0
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
GeneratedFunctionStub at ./boot.jl:582
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
jl_apply at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/julia.h:1843 [inlined]
jl_call_staged at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/method.c:520
ijl_code_for_staged at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/method.c:571
get_staged at ./compiler/utilities.jl:114
retrieve_code_info at ./compiler/utilities.jl:126 [inlined]
InferenceState at ./compiler/inferencestate.jl:284
typeinf_edge at ./compiler/typeinfer.jl:868
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2360
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:647
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:139
abstract_call_known at ./compiler/abstractinterpretation.jl:1716
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_apply at ./compiler/abstractinterpretation.jl:1357
abstract_call_known at ./compiler/abstractinterpretation.jl:1620
abstract_call at ./compiler/abstractinterpretation.jl:1786
abstract_call at ./compiler/abstractinterpretation.jl:1753
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1910
typeinf_local at ./compiler/abstractinterpretation.jl:2386
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2482
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_ext at ./compiler/typeinfer.jl:967
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1000
typeinf_ext_toplevel at ./compiler/typeinfer.jl:996
jfptr_typeinf_ext_toplevel_17873.clone_1 at /home/ptiede/.julia/juliaup/julia-1.8.4+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
jl_apply at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/julia.h:1843 [inlined]
jl_type_infer at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:315
jl_generate_fptr_impl at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/jitlayers.cpp:319
jl_compile_method_internal at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2091 [inlined]
jl_compile_method_internal at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2035
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2369 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
jl_apply at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/julia.h:1843 [inlined]
do_call at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/interpreter.c:126
eval_value at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/interpreter.c:215
eval_stmt_value at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/interpreter.c:166 [inlined]
eval_body at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/interpreter.c:612
jl_interpret_toplevel_thunk at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/interpreter.c:750
jl_toplevel_eval_flex at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/toplevel.c:906
jl_toplevel_eval_flex at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/toplevel.c:850
ijl_toplevel_eval_in at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/toplevel.c:965
eval at ./boot.jl:368 [inlined]
include_string at ./loading.jl:1428
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
_include at ./loading.jl:1488
include at ./Base.jl:419
jfptr_include_47457.clone_1 at /home/ptiede/.julia/juliaup/julia-1.8.4+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
exec_options at ./client.jl:303
_start at ./client.jl:522
jfptr__start_58474.clone_1 at /home/ptiede/.julia/juliaup/julia-1.8.4+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/gf.c:2559
jl_apply at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/julia.h:1843 [inlined]
true_main at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/jlapi.c:575
jl_repl_entrypoint at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/src/jlapi.c:719
main at /cache/build/default-aws-shared0-3/julialang/julia-release-1-dot-8/cli/loader_exe.c:59
unknown function (ip: 0x7fa422d4f28f)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x401098)
Allocations: 28645079 (Pool: 28621680; Big: 23399); GC: 34
[1]    78378 segmentation fault (core dumped)  julia enzyme_test.jl```
```

My computing environment
```julia
Julia Version 1.8.4
Commit 00177ebc4fc (2022-12-23 21:32 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 1
```

**Comment by wsmoses** [comment] 2023-01-06 04:11
Is the error deterministic? Unfortunately I cannot reproduce it.

**Comment by ptiede** [comment] 2023-01-06 14:07
I tested this on 1.9.0-beta2 and 1.8.4 on a I seem to always get this segfault.

**Comment by ChrisRackauckas** [comment] 2023-01-08 03:36
Seems like there's a lot of them: https://github.com/SciML/DiffEqNoiseProcess.jl/actions/runs/3865111555/jobs/6588398986

Maybe the latest release should be yanked?

**Comment by wsmoses** [comment] 2023-01-08 23:09
This should be fixed by https://github.com/EnzymeAD/Enzyme.jl/pull/574 test it out?

**Comment by wsmoses** [comment] 2023-01-09 02:40
Fix landed on main, reopen if this persists.

**Closed by wsmoses** 2023-01-09 02:40 UTC

**Comment by ptiede** [comment] 2023-01-09 15:37
Works, thanks so much!
