### ISSUE TITLE
Type insertion error

### ISSUE THREAD

**Issue by swilliamson7** [EnzymeAD/Enzyme.jl#646] opened 2023-03-03 21:05 UTC
I'm not sure if this is expected behavior or not, but when I run the following:

```julia
using Enzyme, Parameters

mutable struct gyre_vector
    u::Vector{Float64}
    v::Vector{Float64}
    eta::Vector{Float64}
end

@with_kw struct RHS_terms_debug
    Nu::Int
    u0::Vector{Float64} = zeros(Nu) 
end

function advance(u_v_eta, rhs)

    rk_b = [1/2, 1/2, 1]
    rhs.u0 .= u_v_eta.u
    rhs.u0 .= rhs.u0 

    copyto!(u_v_eta.u, rhs.u0)

    return nothing 

end 

nx = 5             # grid resolution in x-direction
ny = 5             # grid resolution in y-direction

NT = nx * ny 
Nu = (nx - 1) * ny 
Nv = (ny - 1) * nx 
Nq = (nx + 1) * (ny + 1)

rhs_terms = RHS_terms_debug(Nu = Nu)
ad_rhs_terms = RHS_terms_debug(Nu = Nu)

u_v_eta = gyre_vector(zeros(Nu), zeros(Nv), zeros(NT))
ad_u_v_eta = gyre_vector(zeros(Nu), zeros(Nv), zeros(NT))


# checking that the function does in fact run
advance(u_v_eta, rhs_terms)

autodiff(advance,
    Duplicated(u_v_eta, ad_u_v_eta),
    Duplicated(rhs_terms, ad_rhs_terms)
)
```

I get this error: 

```julia 
inserting into : {[1]:Integer, [2]:Integer, [3]:Integer, [4]:Integer, [5]:Integer, [6]:Integer, [7]:Integer} with [-1] of Float@double
illegal insertion
UNREACHABLE executed at /workspace/srcdir/Enzyme/enzyme/Enzyme/TypeAnalysis/TypeTree.h:213!

signal (6): Abort trap: 6
in expression starting at /Users/swilliamson/Documents/GitHub/eddy-stresses/src/enzyme_1.jl:46
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 28688769 (Pool: 28666036; Big: 22733); GC: 33
zsh: abort      julia --project=. ./src/enzyme_1.jl
```

The error goes away though when I instead define `rk_b` as `rk_b = [1/2, 1/2, 1.]`. Is this normal? I'm not even using the 1 from that vector when I get the error. I'm on Julia version 1.8.5 and Enzyme v0.10.18, if that helps.

**Comment by wsmoses** [comment] 2023-03-04 03:54
Can you retry on main and also add a Enzyme.API.printtype!(true) and attach the log?

**Comment by wsmoses** [comment] 2023-03-05 21:31
@swilliamson7 I cannot reproduce your error on current main/julia 1.9.

**Comment by wsmoses** [comment] 2023-03-05 21:36
I can reproduce on 1.8.4

**Comment by wsmoses** [comment] 2023-03-05 21:40
Reduced:
```julia
wmoses@beast:~/git/Enzyme.jl (fcal) $ cat s.jl 
using Enzyme
Enzyme.API.printall!(true)
Enzyme.API.printtype!(true)

function advance()
    rk_b = [1/2, 1/2, 1]
    return nothing
end

autodiff(Reverse, advance)
```

**Comment by wsmoses** [comment] 2023-03-05 21:46
Okay the issue here is that the differing type of 1/2, and 1 means that this array is a union. This is fixed by inserting a call to Enzyme.API.strictAliasing!(true), or as you have setting 1 -> 1.0

**Closed by wsmoses** 2023-03-05 21:46 UTC
