### ISSUE TITLE
Found unhandled active variable in tuple splat

### ISSUE THREAD

**Issue by aplavin** [EnzymeAD/Enzyme.jl#1255] opened 2024-01-28 14:24 UTC
Constructing tuples larger than a certain length throws this error that I couldn't even understand. MWE:
```julia
using Enzyme

function f(x)
	res = NTuple{40}(x)
	return res[1]
end

x = ones(40)
δδx = zeros(40)

(_, y) = Enzyme.autodiff(Enzyme.ReverseWithPrimal, f, Enzyme.Active, Enzyme.Duplicated(x, δδx))

# error:
AssertionError: Found unhandled active variable in tuple splat, jl_apply_iterate Tuple{Float64}
error_if_active_iter(::Base.RefValue{Tuple{Float64}})@jitrules.jl:775
_totuple@tuple.jl:410[inlined]
_totuple@tuple.jl:409[inlined]
Tuple@tuple.jl:391
...
```
The same code works if 40 is replaced with, say, 20.

How can this be fixed?

**Comment by wsmoses** [comment] 2024-01-28 18:49
If you actually make this type stable, like below, it does not error:

```julia
using Enzyme


function f(x)
	res = ntuple(Val(40)) do i
		Base.@_inline_meta
		x[i]
	end
	return res[1]
end

x = ones(40)
δδx = zeros(40)

(_, y) = Enzyme.autodiff(Enzyme.ReverseWithPrimal, f, Enzyme.Active, Enzyme.Duplicated(x, δδx))

((nothing,), 1.0)
```

**Comment by wsmoses** [comment] 2024-01-28 18:50
Now closing as duplicate of https://github.com/EnzymeAD/Enzyme.jl/issues/1235

If you'd like, feel free to open an issue on the Julia compiler itself (https://github.com/JuliaLang/julia) for the NTuple constructor not being type stable

**Closed by wsmoses** 2024-01-28 18:50 UTC

**Comment by wsmoses** [comment] 2024-01-28 19:21
Yeah this is a question better posed to JuliaLang/julia at this point. All I can tell you is that the llvm the Julia compiler makes is type unstable by the time Enzyme gets it for your test case.

Feel free to cc me though.
