### ISSUE TITLE
Seg fault with tutorial code 

### ISSUE THREAD

**Issue by swilliamson7** [EnzymeAD/Enzyme.jl#536] opened 2022-10-25 22:55 UTC
I was working on updating the Enzyme tutorial, and I'm reaching a segfault just with the code that Michel had shared, just an edited version of what I'd originally wrote:

```
using Enzyme

const blength = [5000.0e5; 1000.0e5; 5000.0e5]   ## north-south size of boxes, centimeters

const bdepth = [1.0e5; 5.0e5; 4.0e5]   ## depth of boxes, centimeters

const delta = bdepth[1]/(bdepth[1] + bdepth[3])  ## constant ratio of two depths

const bwidth = 4000.0*1e5  ## box width, centimeters

## box areas
const barea = [blength[1]*bwidth;
         blength[2]*bwidth;
         blength[3]*bwidth]

## box volumes
const bvol = [barea[1]*bdepth[1];
        barea[2]*bdepth[2];
        barea[3]*bdepth[3]]

## parameters that are used to ensure units are in CGS (cent-gram-sec)

const hundred = 100.0
const thousand = 1000.0
const day = 3600.0*24.0
const year = day*365.0
const Sv = 1e12     ## one Sverdrup (a unit of ocean transport), 1e6 meters^3/second

## parameters that appear in box model equations
const u0 = 16.0*Sv/0.0004
const alpha = 1668e-7
const beta = 0.7811e-3

const gamma = 1/(300*day)

## robert filter coefficient for the smoother part of the timestep
const robert_filter_coeff = 0.25

## freshwater forcing
const FW = [(hundred/year) * 35.0 * barea[1]; -(hundred/year) * 35.0 * barea[1]]

## restoring atmospheric temperatures
const Tstar = [22.0; 0.0]
const Sstar = [36.0; 34.0];


## function to compute transport
##       Input: rho - the density vector
##       Output: U - transport value

function U_func(dens)

    U = u0*(dens[2] - (delta * dens[1] + (1 - delta)*dens[3]))
    return U

end

## function to compute density
##       Input: state = [T1; T2; T3; S1; S2; S3]
##       Output: rho

function rho_func(state)

    rho = zeros(3)

    rho[1] = -alpha * state[1] + beta * state[4]
    rho[2] = -alpha * state[2] + beta * state[5]
    rho[3] = -alpha * state[3] + beta * state[6]

    return rho

end

## lastly our timestep function
##       Input: fld_now = [T1(t), T2(t), ..., S3(t)]
##           fld_old = [T1(t-dt), ..., S3(t-dt)]
##           u = transport(t)
##           dt = time step
##       Output: fld_new = [T1(t+dt), ..., S3(t+dt)]

function timestep_func(fld_now, fld_old, u, dt)

    temp = zeros(6)
    fld_new = zeros(6)

    ## first computing the time derivatives of the various temperatures and salinities
    if u > 0

        temp[1] = u * (fld_now[3] - fld_now[1]) / bvol[1] + gamma * (Tstar[1] - fld_now[1])
        temp[2] = u * (fld_now[1] - fld_now[2]) / bvol[2] + gamma * (Tstar[2] - fld_now[2])
        temp[3] = u * (fld_now[2] - fld_now[3]) / bvol[3]

        temp[4] = u * (fld_now[6] - fld_now[4]) / bvol[1] + FW[1] / bvol[1]
        temp[5] = u * (fld_now[4] - fld_now[5]) / bvol[2] + FW[2] / bvol[2]
        temp[6] = u * (fld_now[5] - fld_now[6]) / bvol[3]

    elseif u <= 0

        temp[1] = u * (fld_now[2] - fld_now[1]) / bvol[1] + gamma * (Tstar[1] - fld_now[1])
        temp[2] = u * (fld_now[3] - fld_now[2]) / bvol[2] + gamma * (Tstar[2] - fld_now[2])
        temp[3] = u * (fld_now[1] - fld_now[3]) / bvol[3]

        temp[4] = u * (fld_now[5] - fld_now[4]) / bvol[1] + FW[1] / bvol[1]
        temp[5] = u * (fld_now[6] - fld_now[5]) / bvol[2] + FW[2] / bvol[2]
        temp[6] = u * (fld_now[4] - fld_now[6]) / bvol[3]

    end

    ## update fldnew using a version of Euler's method

    for j = 1:6
        fld_new[j] = fld_old[j] + 2.0 * dt * temp[j]
    end

    return fld_new
end

# ## Define forward functions

function forward_func(state, fld_old, fld_now, dt, M)

    state_now = copy(fld_now)
    state_old = copy(fld_old)
    state_new = zeros(6)

    for t = 1:M
        rho_now = rho_func(state_now)
        u_now = U_func(rho_now)
        state_new = timestep_func(state_now, state_old, u_now, dt)

        ## Robert filter smoother (needed for stability)
        for j = 1:6
            state_now[j] = state_now[j] + robert_filter_coeff * (state_new[j] - 2.0 * state_now[j] + state_old[j])
        end

        ## cycle the "now, new, old" states

        state_old = state_now
        state_now = state_new
    end
    copyto!(state, state_old)

    return nothing
end

const Tbar = [20.0; 1.0; 1.0]
const Sbar = [35.5; 34.5; 34.5]

const M = 10000             ## Deciding on total number of forward steps to take

## unperturbed final state

state_out = zeros(6)
forward_func(state_out, [Tbar;Sbar], [Tbar;Sbar], 10*day, M)
use_to_check = state_out[1]


din_now = zeros(6)
din_old = zeros(6)
dout_old = [1.0;0.0;0.0;0.0;0.0;0.0]
dout_now = [0.0;0.0;0.0;0.0;0.0;0.0]
state_out = zeros(6)
autodiff(
    forward_func,
    Duplicated(state_out, dout_old),
    Duplicated([Tbar; Sbar], din_now),
    Duplicated([Tbar; Sbar], din_old),
    10*day,
    M,
)
```

This led to this output: 

> signal (11): Segmentation fault: 11
> in expression starting at /Users/swilliamson/Documents/issue.jl:163
> _Z14PostCacheStorePN4llvm9StoreInstERNS_9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultInserterEEE at /Users/swilliamson/.julia/artifacts/8493c1f4eee1ef957152a9877681c9150152f160/lib/libEnzyme-13.dylib (unknown line)
> _ZN12CacheUtility23storeInstructionInCacheENS_12LimitContextERN4llvm9IRBuilderINS1_14ConstantFolderENS1_24IRBuilderDefaultInserterEEEPNS1_5ValueEPNS1_10AllocaInstEPNS1_6MDNodeE at /Users/swilliamson/.julia/artifacts/8493c1f4eee1ef957152a9877681c9150152f160/lib/libEnzyme-13.dylib (unknown line)
> _ZN12CacheUtility23storeInstructionInCacheENS_12LimitContextEPN4llvm11InstructionEPNS1_10AllocaInstEPNS1_6MDNodeE at /Users/swilliamson/.julia/artifacts/8493c1f4eee1ef957152a9877681c9150152f160/lib/libEnzyme-13.dylib (unknown line)
> _ZN13GradientUtils18ensureLookupCachedEPN4llvm11InstructionEbPNS0_10BasicBlockEPNS0_6MDNodeE at /Users/swilliamson/.julia/artifacts/8493c1f4eee1ef957152a9877681c9150152f160/lib/libEnzyme-13.dylib (unknown line)
> _ZN13GradientUtils7lookupMEPN4llvm5ValueERNS0_9IRBuilderINS0_14ConstantFolderENS0_24IRBuilderDefaultInserterEEERKNS0_8ValueMapIPKS1_NS0_14WeakTrackingVHENS0_14ValueMapConfigISA_NS0_3sys10SmartMutexILb0EEEEEEEb at /Users/swilliamson/.julia/artifacts/8493c1f4eee1ef957152a9877681c9150152f160/lib/libEnzyme-13.dylib (unknown line)
> _ZN16AdjointGeneratorIPK15AugmentedReturnE6lookupEPN4llvm5ValueERNS4_9IRBuilderINS4_14ConstantFolderENS4_24IRBuilderDefaultInserterEEE at /Users/swilliamson/.julia/artifacts/8493c1f4eee1ef957152a9877681c9150152f160/lib/libEnzyme-13.dylib (unknown line)
> _ZN16AdjointGeneratorIPK15AugmentedReturnE13visitCallInstERN4llvm8CallInstE at /Users/swilliamson/.julia/artifacts/8493c1f4eee1ef957152a9877681c9150152f160/lib/libEnzyme-13.dylib (unknown line)
> _ZN11EnzymeLogic23CreatePrimalAndGradientEOK15ReverseCacheKeyR12TypeAnalysisPK15AugmentedReturnb at /Users/swilliamson/.julia/artifacts/8493c1f4eee1ef957152a9877681c9150152f160/lib/libEnzyme-13.dylib (unknown line)
> EnzymeCreatePrimalAndGradient at /Users/swilliamson/.julia/artifacts/8493c1f4eee1ef957152a9877681c9150152f160/lib/libEnzyme-13.dylib (unknown line)
> EnzymeCreatePrimalAndGradient at /Users/swilliamson/.julia/dev/Enzyme/src/api.jl:118
> enzyme! at /Users/swilliamson/.julia/dev/Enzyme/src/compiler.jl:4508
> unknown function (ip: 0x13749a21b)
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> #codegen#120 at /Users/swilliamson/.julia/dev/Enzyme/src/compiler.jl:5498
> codegen##kw at /Users/swilliamson/.julia/dev/Enzyme/src/compiler.jl:5168 [inlined]
> _thunk at /Users/swilliamson/.julia/dev/Enzyme/src/compiler.jl:5971 [inlined]
> _thunk at /Users/swilliamson/.julia/dev/Enzyme/src/compiler.jl:5965
> unknown function (ip: 0x1344cc463)
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> cached_compilation at /Users/swilliamson/.julia/dev/Enzyme/src/compiler.jl:6009
> unknown function (ip: 0x1340003db)
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> #s753#147 at /Users/swilliamson/.julia/dev/Enzyme/src/compiler.jl:6069 [inlined]
> #s753#147 at ./none:0
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> GeneratedFunctionStub at ./boot.jl:582
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_call_staged at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> ijl_code_for_staged at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> get_staged at ./compiler/utilities.jl:114
> retrieve_code_info at ./compiler/utilities.jl:126 [inlined]
> InferenceState at ./compiler/inferencestate.jl:284
> typeinf_edge at ./compiler/typeinfer.jl:868
> abstract_call_method at ./compiler/abstractinterpretation.jl:641
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:153
> abstract_call_known at ./compiler/abstractinterpretation.jl:1696
> abstract_call at ./compiler/abstractinterpretation.jl:1766
> abstract_call at ./compiler/abstractinterpretation.jl:1733
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
> typeinf_local at ./compiler/abstractinterpretation.jl:2366
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
> _typeinf at ./compiler/typeinfer.jl:230
> typeinf at ./compiler/typeinfer.jl:213
> typeinf_edge at ./compiler/typeinfer.jl:877
> abstract_call_method at ./compiler/abstractinterpretation.jl:641
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:153
> abstract_call_known at ./compiler/abstractinterpretation.jl:1696
> abstract_call at ./compiler/abstractinterpretation.jl:1766
> abstract_call at ./compiler/abstractinterpretation.jl:1733
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
> typeinf_local at ./compiler/abstractinterpretation.jl:2366
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
> _typeinf at ./compiler/typeinfer.jl:230
> typeinf at ./compiler/typeinfer.jl:213
> typeinf_edge at ./compiler/typeinfer.jl:877
> abstract_call_method at ./compiler/abstractinterpretation.jl:641
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:153
> abstract_call_known at ./compiler/abstractinterpretation.jl:1696
> abstract_call at ./compiler/abstractinterpretation.jl:1766
> abstract_call at ./compiler/abstractinterpretation.jl:1733
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
> typeinf_local at ./compiler/abstractinterpretation.jl:2366
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
> _typeinf at ./compiler/typeinfer.jl:230
> typeinf at ./compiler/typeinfer.jl:213
> typeinf_ext at ./compiler/typeinfer.jl:967
> typeinf_ext_toplevel at ./compiler/typeinfer.jl:1000
> typeinf_ext_toplevel at ./compiler/typeinfer.jl:996
> jfptr_typeinf_ext_toplevel_12299 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_type_infer at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_generate_fptr_impl at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-codegen.1.8.dylib (unknown line)
> jl_compile_method_internal at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> autodiff at /Users/swilliamson/.julia/dev/Enzyme/src/Enzyme.jl:300
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> do_apply at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> autodiff at /Users/swilliamson/.julia/dev/Enzyme/src/Enzyme.jl:334
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> do_apply at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> autodiff at /Users/swilliamson/.julia/dev/Enzyme/src/Enzyme.jl:434
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> do_call at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> eval_body at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_interpret_toplevel_thunk at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_toplevel_eval_flex at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_toplevel_eval_flex at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> ijl_toplevel_eval_in at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> eval at ./boot.jl:368 [inlined]
> include_string at ./loading.jl:1428
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> _include at ./loading.jl:1488
> include at ./client.jl:476
> unknown function (ip: 0x102cc4057)
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> do_call at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> eval_body at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_interpret_toplevel_thunk at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_toplevel_eval_flex at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_toplevel_eval_flex at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> ijl_toplevel_eval_in at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> eval at ./boot.jl:368 [inlined]
> eval_user_input at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:151
> repl_backend_loop at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:247
> start_repl_backend at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:232
> #run_repl#47 at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:369
> run_repl at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:355
> jfptr_run_repl_67919 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> #966 at ./client.jl:419
> jfptr_YY.966_42132 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_f__call_latest at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> #invokelatest#2 at ./essentials.jl:729 [inlined]
> invokelatest at ./essentials.jl:726 [inlined]
> run_main_repl at ./client.jl:404
> exec_options at ./client.jl:318
> _start at ./client.jl:522
> jfptr__start_58825 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
> ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> true_main at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> jl_repl_entrypoint at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
> Allocations: 30280287 (Pool: 30239469; Big: 40818); GC: 34 

I don't see anything obvious about why this is happening, could you maybe give some advice?

**Comment by wsmoses** [comment] 2022-10-27 21:02
Can you remove the LocalPreferences.toml we made earlier, and try again?

**Comment by swilliamson7** [comment] 2022-10-27 21:16
Sure and still reached a segfault. Did it run for you? I did try having someone else in my lab run the script and they also got the same error on their computer, also checked that it runs without the autodiff call

**Comment by wsmoses** [comment] 2022-10-27 21:17
It did run for me, though I'm on a later Enzyme_jll (current main) as well as Enzyme.jl main.

**Comment by swilliamson7** [comment] 2022-10-27 21:21
Weird, not sure then

**Comment by wsmoses** [comment] 2022-12-23 22:04
Going to close this as cannot reproduce on current main. Please reopen if it persists.

**Closed** 2022-12-24 07:54 UTC
