### ISSUE TITLE
Support for BigFloat

### ISSUE THREAD

**Issue by LeilaGhaffari** [EnzymeAD/Enzyme.jl#348] opened 2022-05-31 16:44 UTC
It seems that the Julia interface does not support BigFloat. We need this for a stability analysis of our solid mechanics examples. Would it be possible for the Enzyme team to add BigFloat to Enzyme.jl? Thanks!

**Comment by vchuravy** [comment] 2022-05-31 18:31
Duplicate of #346

**Closed by vchuravy** 2022-05-31 18:31 UTC
Labels: enhancement

**Comment by wsmoses** [comment] 2022-05-31 18:32
Wait you can transfer github issues between repos? TIL

**Comment by vchuravy** [comment] 2022-05-31 18:38
Within the same org yes
