### ISSUE TITLE
Reverse mode gradient is up to 100x slower in Enzyme v0.12

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1409] opened 2024-04-29 09:46 UTC
I think it is a consequence of the type instability spotted in #1401

Setup:

```julia
julia> using Chairmarks, Enzyme

julia> f(x) = sum(abs2, x);

julia> bench_outofplace(n) = @b (; x=rand(n),) gradient(Enzyme.Reverse, f, _.x)

julia> bench_inplace(n) = @b (; x=rand(n), g=rand(n)) gradient!(Enzyme.Reverse, _.g, f, _.x) evals=1
```

Out-of-place benchmarks:

| Size | Enzyme v0.11 | Enzyme v0.12 |
|---|---|---|
| 10 | 38.921 ns (1 allocs: 144 bytes) | 3.163 μs (31 allocs: 2.016 KiB, 0.01% compile time) |
| 100 | 424.667 ns (1 allocs: 896 bytes) | 3.766 μs (31 allocs: 2.750 KiB, 0.15% compile time) |
| 1000 | 4.090 μs (1 allocs: 7.938 KiB) | 9.798 μs (31 allocs: 9.812 KiB, <0.01% compile time) |

In-place benchmarks (may be imprecise due to `evals = 1`, see https://chairmarks.lilithhafner.com/v1.2.1/tutorial#Common-pitfalls):

| Size | Enzyme v0.11 | Enzyme v0.12 |
|---|---|---|
| 10 | 25.000 ns | 3.039 μs (28 allocs: 1.547 KiB, <0.01% compile time) |
| 100 | 361.000 ns | 3.438 μs (28 allocs: 1.547 KiB, 0.16% compile time) |
| 1000 | 4.279 μs | 7.439 μs (28 allocs: 1.547 KiB, 0.17% compile time) |

**Comment by adrhill** [comment] 2024-04-29 12:53
I can reproduce this on Enzyme `v0.12.0` and `v0.11.20`.
```Julia
julia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 12 × Apple M3 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 6 virtual cores)
```

**Comment by wsmoses** [comment] 2024-04-29 14:25
My guess is that the recent change to use make zero and thus support more
than just Julia arrays was the cause here.

Will try to look at this week and restore normal array perf.

**Comment by gdalle** [comment] 2024-04-29 14:34
Thanks! If you need beta testers, let me know!

**Comment by wsmoses** [comment] 2024-05-06 20:55
@gdalle can you see if https://github.com/EnzymeAD/Enzyme.jl/pull/1415 resolves the issue?

**Comment by gdalle** [comment] 2024-05-06 21:38
On a slower laptop:

Enzyme 0.11

```julia
julia> bench_inplace(10)
141.000 ns

julia> bench_inplace(100)
866.000 ns

julia> bench_outofplace(10)
140.321 ns (1 allocs: 144 bytes)

julia> bench_outofplace(100)
907.133 ns (1 allocs: 896 bytes)
```

PR on Enzyme 0.12

```julia
julia> bench_inplace(10)
5.569 μs (28 allocs: 1.547 KiB, <0.01% compile time)

julia> bench_inplace(100)
6.383 μs (28 allocs: 1.547 KiB, 0.03% compile time)

julia> bench_outofplace(10)
5.483 μs (29 allocs: 1.688 KiB, 0.03% compile time)

julia> bench_outofplace(100)
6.405 μs (29 allocs: 2.422 KiB, <0.01% compile time)
```

Still not there it seems

**Comment by wsmoses** [comment] 2024-05-07 02:36
Should be fixed by https://github.com/EnzymeAD/Enzyme.jl/pull/1415 please reopen if it persists

**Closed by wsmoses** 2024-05-07 02:36 UTC

**Comment by gdalle** [comment] 2024-05-07 10:19
fixed indeed, good job!
