### ISSUE TITLE
Support for `jl_eqtable_get`

### ISSUE THREAD

**Issue by MasonProtter** [EnzymeAD/Enzyme.jl#803] opened 2023-05-02 21:59 UTC
Not sure if this is something that's reasonable to support in Enzyme or not, but I'll ask anyways. I'm getting a stacktrace
```julia
Enzyme execution failed.
Enzyme: Not yet implemented augmented forward for jl_eqtable_get
Stacktrace:
 [1] get!
   @ ./iddict.jl:176
 [2] default_buffer
   @ ~/Dropbox/Julia/Bumper/src/Bumper.jl:20
```
which is caused by trying to call `get!(::Function, ::IdDict{Any, Any}, ::Symbol)::T` in some evil stuff that Bumper.jl is doing. It'd be nice if this is possible to support.

**Comment by vchuravy** [comment] 2023-05-02 22:24
Can you write a MWE?

**Comment by wsmoses** [comment] 2023-05-02 22:26
Duplicate of https://github.com/EnzymeAD/Enzyme.jl/issues/416

But yes we should add this but haven't gotten to.

**Closed by wsmoses** 2023-05-02 22:26 UTC
