### ISSUE TITLE
Package load time is quite long, and longer on Julia 1.10

### ISSUE THREAD

**Issue by jgreener64** [EnzymeAD/Enzyme.jl#1234] opened 2024-01-02 11:21 UTC
This isn't the end of the world, but something worth keeping an eye on. This is with Enzyme main (443f798457da9295598b47cf2fcfe216ca53a2c7), Ubuntu and 18 threads.
```julia
@time using Enzyme
```
With Julia 1.7.2:
```
  9.343872 seconds (15.13 M allocations: 836.380 MiB, 6.14% gc time, 93.39% compilation time)
```
With Julia 1.8.5:
```
 15.986613 seconds (31.91 M allocations: 1.708 GiB, 6.90% gc time, 91.74% compilation time: 33% of which was recompilation)
```
With Julia 1.9.2:
```
  7.214598 seconds (14.60 M allocations: 988.510 MiB, 7.17% gc time, 91.72% compilation time)
```
With Julia 1.10.0:
```
 13.227393 seconds (17.16 M allocations: 1.194 GiB, 3.57% gc time, 97.53% compilation time)
```

**Comment by wsmoses** [comment] 2024-01-02 18:25
Going to mark as a duplicate of https://github.com/EnzymeAD/Enzyme.jl/issues/506 and https://github.com/EnzymeAD/Enzyme.jl/issues/776

However, the issue presently is partially that the Julia compiler itself is not well tuned to handle the cfunction registration iirc.

cc @vchuravy @KristofferC

**Closed** 2024-01-05 02:06 UTC
