### ISSUE TITLE
Error in precompiling in julia 1.11beta2

### ISSUE THREAD

**Issue by PhyX-Meow** [EnzymeAD/Enzyme.jl#1484] opened 2024-05-30 05:30 UTC
```
In [1]: using Enzyme
Precompiling Enzyme...
Info Given Enzyme was explicitly requested, output will be shown live
ERROR: LoadError: UndefVarError: `CodeCache` not defined in `GPUCompiler`
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:558
 [2] include(x::String)
   @ Enzyme.Compiler ~/.julia/packages/Enzyme/F71IJ/src/compiler.jl:1
 [3] top-level scope
   @ ~/.julia/packages/Enzyme/F71IJ/src/compiler.jl:2799
 [4] include(mod::Module, _path::String)
   @ Base ./Base.jl:558
 [5] include(x::String)
   @ Enzyme ~/.julia/packages/Enzyme/F71IJ/src/Enzyme.jl:1
 [6] top-level scope
   @ ~/.julia/packages/Enzyme/F71IJ/src/Enzyme.jl:46
 [7] include
   @ ./Base.jl:558 [inlined]
 [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2721
 [9] top-level scope
   @ stdin:4
in expression starting at /home/wuli/.julia/packages/Enzyme/F71IJ/src/compiler/interpreter.jl:1
in expression starting at /home/wuli/.julia/packages/Enzyme/F71IJ/src/compiler.jl:1
in expression starting at /home/wuli/.julia/packages/Enzyme/F71IJ/src/Enzyme.jl:1
in expression starting at stdin:4
  ✗ Enzyme
  0 dependencies successfully precompiled in 68 seconds. 49 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

Enzyme

Failed to precompile Enzyme [7da242da-08ed-463a-9acd-ee780be4f1d9] to "/home/wuli/.julia/compiled/v1.11/Enzyme/jl_mh3OQJ".
ERROR: LoadError: UndefVarError: `CodeCache` not defined in `GPUCompiler`
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:558
 [2] include(x::String)
   @ Enzyme.Compiler ~/.julia/packages/Enzyme/F71IJ/src/compiler.jl:1
 [3] top-level scope
   @ ~/.julia/packages/Enzyme/F71IJ/src/compiler.jl:2799
 [4] include(mod::Module, _path::String)
   @ Base ./Base.jl:558
 [5] include(x::String)
   @ Enzyme ~/.julia/packages/Enzyme/F71IJ/src/Enzyme.jl:1
 [6] top-level scope
   @ ~/.julia/packages/Enzyme/F71IJ/src/Enzyme.jl:46
 [7] include
   @ ./Base.jl:558 [inlined]
 [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2721
 [9] top-level scope
   @ stdin:4
in expression starting at /home/wuli/.julia/packages/Enzyme/F71IJ/src/compiler/interpreter.jl:1
in expression starting at /home/wuli/.julia/packages/Enzyme/F71IJ/src/compiler.jl:1
in expression starting at /home/wuli/.julia/packages/Enzyme/F71IJ/src/Enzyme.jl:1
in expression starting at stdin:
```
```
(@v1.11) pkg> st -m GPUCompiler
Status `~/.julia/environments/v1.11/Manifest.toml`
  [61eb1bfa] GPUCompiler v0.26.5

(@v1.11) pkg> st Enzyme
Status `~/.julia/environments/v1.11/Project.toml`
  [7da242da] Enzyme v0.12.9
```

**Comment by vchuravy** [comment] 2024-05-30 12:52
Enzyme does currently not support Julia 1.11

**Comment by PhyX-Meow** [comment] 2024-05-30 12:56
> Enzyme does currently not support Julia 1.11

Cool.

**Comment by wsmoses** [comment] 2024-05-31 21:36
Duplicate of https://github.com/EnzymeAD/Enzyme.jl/issues/1358

**Closed by wsmoses** 2024-05-31 21:36 UTC
