### ISSUE TITLE
Really long error on julia 1.11

### ISSUE THREAD

**Issue by longemen3000** [EnzymeAD/Enzyme.jl#1748] opened 2024-08-23 06:18 UTC
hi,

i was trying to calculate derivatives again (#672), but now the calculation in that issue fails with a really long stacktrace:

MWE:

```
using Clapeyron
using Enzyme

model = BasicIdeal()
v = 0.03
T = 300.0
z = Clapeyron.SA[1.0]
p0 = pressure(model,v,T,z)
p1 = Clapeyron.Rgas()*T/v
function pressure_enzyme(model,v,T,z)
           return -Enzyme.autodiff(Enzyme.Forward,Clapeyron.eos, Const(model), Duplicated(v,one(v)), Const(T), Const(z))[1]
end

pressure_enzyme(model,v,T,z) #works
model2 = vdW("ethane")
pressure_enzyme(model2,v,T,z) #does not work, really long stacktrace
```
the stracktrace is the following.
https://pastebin.com/8JVavQ7P

version info:
```
julia> versioninfo()
Julia Version 1.11.0-rc2
Commit 34c3a63147 (2024-07-29 06:24 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, haswell)
Threads: 4 default, 0 interactive, 2 GC (on 8 virtual cores)
Environment:
  JULIA_NUM_THREADS = 4
```

Packages: Clapeyron 0.6.2, Enzyme v0.12.31

**Comment by wsmoses** [comment] 2024-08-25 20:16
We should fix this, but to set expectations, Enzyme.jl does not currently support 1.11, try 1.10?

**Comment by wsmoses** [comment] 2024-08-26 01:38
I can't reproduce this, though I used 1.11-beta2 and current enzyme main. Can you retry on latest Enzyme and see if it still occurs?

**Comment by longemen3000** [comment] 2024-08-26 01:59
the error still appears on v0.12.32.

**Comment by wsmoses** [comment] 2024-08-26 04:36
yeah I still can't repro:
```julia
julia> using Enzyme

julia> model = BasicIdeal()
BasicIdeal()

julia> v = 0.03
0.03

julia> T = 300.0
300.0

julia> z = Clapeyron.SA[1.0]
1-element StaticArraysCore.SVector{1, Float64} with indices SOneTo(1):
 1.0

julia> p0 = pressure(model,v,T,z)
83144.62618153241

julia> p1 = Clapeyron.Rgas()*T/v
83144.62618153241

julia> function pressure_enzyme(model,v,T,z)
                  return -Enzyme.autodiff(Enzyme.Forward,Clapeyron.eos, Const(model), Duplicated(v,one(v)), Const(T), Const(z))[1]
       end
pressure_enzyme (generic function with 1 method)

julia> pressure_enzyme(model,v,T,z) #works
83144.62618153241

julia> model2 = vdW("ethane")
vdW{BasicIdeal, NoAlpha, NoTranslation, vdW1fRule} with 1 component:
 "ethane"
Contains parameters: a, b, Tc, Pc, Mw

julia> pressure_enzyme(model2,v,T,z) #does not work, really long stacktrace
82703.51016122995

julia> versioninfo()
Julia Version 1.11.0-rc2
Commit 34c3a63147* (2024-07-29 06:24 UTC)
Build Info:
  DEBUG build

    Note: This is an unofficial build, please report bugs to the project
    responsible for this build and not to the Julia project unless you can
    reproduce the issue using official builds available at https://julialang.org/downloads

Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 64 × AMD Ryzen Threadripper 3970X 32-Core Processor
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 64 virtual cores)
Environment:
  LD_LIBRARY_PATH = :/home/wmoses/.local/lib
  ```

**Comment by longemen3000** [comment] 2024-08-26 05:30
i'm on windows, maybe it has something to do with that?, im gonna try to reproduce this on CI, if it does not reproduce, then i will close

**Comment by longemen3000** [comment] 2024-08-27 22:09
it still happens on rc3, but it does not reproduce on CI :( , probably my system does not have something that enzyme needs

**Comment by wsmoses** [comment] 2024-09-03 00:31
Resolved by https://github.com/EnzymeAD/Enzyme.jl/pull/1777

**Closed by wsmoses** 2024-09-03 00:31 UTC
Labels: more information needed
