### ISSUE TITLE
Error when range step is not 1

### ISSUE THREAD

**Issue by jgreener64** [EnzymeAD/Enzyme.jl#1196] opened 2023-12-15 11:07 UTC
The following errors on Enzyme main (617ecaf) and Julia 1.9.2.
```julia
using Enzyme
f(x) = sum(1.0:0.1:2.0) * x
autodiff(Reverse, f, Active, Active(2.0))
```
The [error.txt](https://github.com/EnzymeAD/Enzyme.jl/files/13684442/error.txt) and [printall_error.txt](https://github.com/EnzymeAD/Enzyme.jl/files/13684416/printall_error.txt) are attached. When the step is `1.0` not `0.1` it works okay.

**Comment by vchuravy** [comment] 2023-12-15 11:54
```
cannot handle unknown binary operator:   %197 = and i64 %194, %196, !dbg !340


Stacktrace:
 [1] &
   @ ./int.jl:347
 [2] truncmask
   @ ./twiceprecision.jl:29
 [3] truncbits
   @ ./twiceprecision.jl:34
 [4] *
   @ ./twiceprecision.jl:314
 [5] sum
   @ ./twiceprecision.jl:620
```

So duplicate of #274

@jgreener64 for this we will need to define custom rules.

**Comment by wsmoses** [comment] 2023-12-15 16:21
Yeah closing as duplicate

**Closed by wsmoses** 2023-12-15 16:21 UTC
