### ISSUE TITLE
Segment violation when trying to run an optimization problem with DiffEqFlux.jl

### ISSUE THREAD

**Issue by jarroyoe** [EnzymeAD/Enzyme.jl#634] opened 2023-02-21 20:21 UTC
I'm trying to run the following code, which is being discussed in [this issue of DiffEqFlux](https://github.com/SciML/DiffEqFlux.jl/issues/812).
```
using Lux, DiffEqFlux, DifferentialEquations, Optimization, OptimizationOptimJL, OptimizationOptimisers
using Random, StatsBase
using Plots
using DelimitedFiles, Serialization
rng = Random.default_rng()

chain = Lux.Chain(Lux.Dense(10,30),Lux.Dense(30,20),Lux.Dense(20,10))
knownDynamics(x,m,q) = -m.*x
ps, st = Lux.setup(rng, chain)
ps_dynamics = Lux.ComponentVector((predefined_params = rand(Float32, 1), model_params = ps))

function ude!(du,u,p,t,q)
        knownPred = knownDynamics(u,p.predefined_params,q)
        nnPred = Array(chain(u,p.model_params,st)[1])

        for i in 1:length(u)
            du[i] = knownPred[i]+nnPred[i]
        end
end

nn_dynamics!(du,u,p,t) = ude!(du,u,p,t,nothing)
training_data = rand(Float32,10,50)
prob_nn = ODEProblem(nn_dynamics!,training_data[:, 1], (Float32(1),Float32(size(training_data,2))), ps_dynamics)

function predict(p, X = training_data[:,1], T = 1:size(training_data,2))
        _prob = remake(prob_nn, u0 = X, tspan = (T[1], T[end]), p = p)
        Array(solve(_prob, Tsit5(), saveat = T,
                abstol=1e-6, reltol=1e-6
                ))
end

    # Simple L2 loss
function loss(p)
        X̂ = predict(p)
        sum(abs2, training_data .- X̂)
end

losses = Float64[]

callback = function (p, l)
      push!(losses, l)
    if length(losses)%50==0
          println("Current loss after $(length(losses)) iterations: $(losses[end])")
    end
    return false
end

adtype = Optimization.AutoZygote()
optf = Optimization.OptimizationFunction((x,p)->loss(x), adtype)
optprob = Optimization.OptimizationProblem(optf, ps_dynamics)
res1 = Optimization.solve(optprob, ADAM(), callback=callback, maxiters = 1000)
```
Running it leads to the following LLVM error:
```
signal (11): Segment violation
in expression starting at REPL[21]:1
unknown function (ip: 0x7ff1e1ea1995)
unknown function (ip: 0x7ff1e1ea5fd7)
ijl_gc_collect at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
ijl_gc_pool_alloc at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
unknown function (ip: 0x7ff1c058527f)
unknown function (ip: 0x7ff1c0585100)
unknown function (ip: 0x7ff1c0583179)
unknown function (ip: 0x7ff1c0580f1c)
unknown function (ip: 0x7ff1c0579aec)
unknown function (ip: 0x7ff1c04cd8cf)
ssa_inlining_pass! at ./compiler/ssair/inlining.jl:85
unknown function (ip: 0x7ff06873a911)
run_passes at ./compiler/optimize.jl:539
optimize at ./compiler/optimize.jl:504 [inlined]
_typeinf at ./compiler/typeinfer.jl:257
typeinf at ./compiler/typeinfer.jl:213
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:850
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:162
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2366
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:850
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:162
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2340
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:850
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:162
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2340
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:850
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:162
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2366
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:850
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:162
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2366
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:850
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:162
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2366
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:850
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:162
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2366
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:850
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:162
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2366
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:641
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:153
abstract_call at ./compiler/abstractinterpretation.jl:1764
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2366
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:641
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:153
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2366
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_edge at ./compiler/typeinfer.jl:877
abstract_call_method at ./compiler/abstractinterpretation.jl:641
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:153
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
unknown function (ip: 0x7ff06872e519)
unknown function (ip: 0x7ff06871be0d)
unknown function (ip: 0x7ff06871bd7d)
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2366
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_ext at ./compiler/typeinfer.jl:967
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1000
ci_cache_populate at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/jlgen.jl:304
unknown function (ip: 0x7ff0687bec87)
#compile_method_instance#65 at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/jlgen.jl:355
compile_method_instance##kw at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/jlgen.jl:348 [inlined]
macro expansion at /home/jorge/.julia/packages/TimerOutputs/LHjFw/src/TimerOutput.jl:253 [inlined]
#irgen#69 at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/irgen.jl:5
irgen##kw at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/irgen.jl:3 [inlined]
macro expansion at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/driver.jl:215 [inlined]
macro expansion at /home/jorge/.julia/packages/TimerOutputs/LHjFw/src/TimerOutput.jl:253 [inlined]
macro expansion at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/driver.jl:214 [inlined]
#emit_llvm#113 at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/utils.jl:83
unknown function (ip: 0x7ff06870a557)
unknown function (ip: 0x7ff068bc49dd)
unknown function (ip: 0x7ff068bc49a5)
emit_llvm##kw at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/utils.jl:77 [inlined]
#codegen#111 at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/driver.jl:115
codegen##kw at /home/jorge/.julia/packages/GPUCompiler/kb6yJ/src/driver.jl:86
unknown function (ip: 0x7ff068bc4a8c)
#codegen#142 at /home/jorge/.julia/packages/Enzyme/DIkTv/src/compiler.jl:6073
codegen##kw at /home/jorge/.julia/packages/Enzyme/DIkTv/src/compiler.jl:6052 [inlined]
_thunk at /home/jorge/.julia/packages/Enzyme/DIkTv/src/compiler.jl:6870 [inlined]
_thunk at /home/jorge/.julia/packages/Enzyme/DIkTv/src/compiler.jl:6864
unknown function (ip: 0x7ff0683105e1)
cached_compilation at /home/jorge/.julia/packages/Enzyme/DIkTv/src/compiler.jl:6908
unknown function (ip: 0x7ff068b81187)
#s883#169 at /home/jorge/.julia/packages/Enzyme/DIkTv/src/compiler.jl:6968 [inlined]
#s883#169 at ./none:0
unknown function (ip: 0x7ff1c00daae4)
unknown function (ip: 0x7ff1e1eac0a0)
ijl_code_for_staged at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
unknown function (ip: 0x7ff1bfeb2541)
unknown function (ip: 0x7ff1c07843f9)
unknown function (ip: 0x7ff1c0789be2)
unknown function (ip: 0x7ff1c05c59b8)
unknown function (ip: 0x7ff1c056de48)
unknown function (ip: 0x7ff1c05504c8)
unknown function (ip: 0x7ff1c0553c13)
unknown function (ip: 0x7ff1c078cb48)
unknown function (ip: 0x7ff1c0590380)
unknown function (ip: 0x7ff1c059750a)
unknown function (ip: 0x7ff1c059a52d)
unknown function (ip: 0x7ff1c059b3d8)
unknown function (ip: 0x7ff1c078462b)
unknown function (ip: 0x7ff1c0789e89)
unknown function (ip: 0x7ff1c05c59b8)
unknown function (ip: 0x7ff1c056de48)
unknown function (ip: 0x7ff1c05504c8)
unknown function (ip: 0x7ff1c0553c13)
unknown function (ip: 0x7ff1c078cb48)
unknown function (ip: 0x7ff1c0590380)
unknown function (ip: 0x7ff1c059750a)
unknown function (ip: 0x7ff1c059a52d)
unknown function (ip: 0x7ff1c059b3d8)
unknown function (ip: 0x7ff1c078462b)
unknown function (ip: 0x7ff1c05897e6)
unknown function (ip: 0x7ff1bfeb494e)
unknown function (ip: 0x7ff1bfeb442d)
unknown function (ip: 0x7ff1bfeb4472)
jl_type_infer at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
jl_generate_fptr_impl at /usr/bin/../lib64/julia/libjulia-codegen.so.1 (unknown line)
jl_compile_method_internal at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
ijl_apply_generic at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
unknown function (ip: 0x7ff0686d3611)
Allocations: 540052060 (Pool: 539920618; Big: 131442); GC: 111
Segment violation (`core' generado)
```
For some random seeds, I get the following warning for several iterations before the code fails and gets the segment violation error.
```
warning: Linking two modules of different target triples: 'bcloader' is 'x86_64-unknown-linux-gnu' whereas 'text' is 'x86_64-redhat-linux'

┌ Warning: Using fallback BLAS replacements, performance may be degraded
└ @ Enzyme.Compiler ~/.julia/packages/GPUCompiler/kb6yJ/src/utils.jl:50
```

**Comment by wsmoses** [comment] 2023-02-24 01:57
Duplicate of https://github.com/SciML/DiffEqFlux.jl/issues/812

**Comment by wsmoses** [comment] 2023-02-24 01:57
If this isn't fixed on main reopen, but otherwise I presume this is a DiffEqFlux is not on the latest Enzyme issue.

**Closed by wsmoses** 2023-02-24 01:57 UTC
