### ISSUE TITLE
No augmented forward pass found for dgemqrt_64_

### ISSUE THREAD

**Issue by Roger-luo** [EnzymeAD/Enzyme.jl#1037] opened 2023-09-01 14:16 UTC
Enzyme currently fails for a simple linear algebra differentiation, I'm not sure if this is supposed to work or it requires a custom rule, also I'm wondering where are the custom rules defined nowadays?

```julia
using Enzyme
f(x) = sum(Matrix(qr(x).Q))
autodiff(Reverse, f, Duplicated(rand(2, 2), zeros(2, 2))) # boom!
```

it seems reaching the routine defined in LAPACK and stop there, perhaps should have this defined upstream?

**Comment by wsmoses** [comment] 2023-09-01 15:05
Sorry, closing as duplicate of the aforementioned lapack issue

**Closed by wsmoses** 2023-09-01 15:05 UTC
